minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - '@ariestools/*'
  - "@xyo-network/*"

verifyDepsBeforeRun: false

allowBuilds:
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  protobufjs: true
  unrs-resolver: true
